# Generated by Django 5.2.2 on 2025-06-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_order_number_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('post', 'Почта')], default='pickup', max_length=10),
        ),
    ]
