# Generated by Django 5.2.2 on 2025-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_surname',
            field=models.CharField(default='Неизвестно', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Неизвестно', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
